Adapt code to overcome differences of twinBASIC with VBA
cristianbuse/VBA-MemoryTools pull request #10
Opened 2023-10-25 00:48 UTC by Theadd

Hi @cristianbuse ,

Latest changes from `LibMemory`, adding the `TWINBASIC` compiler flag, made using it from `twinBASIC` quite pointless, as it falls to use slower calls, specially in Win32 office, to the `RtlMoveMemory` API everywhere.

1. Adapted `MemByte`, `MemInt`, `MemLong`, `MemLongLong` and `MemLongPtr` to use the built-in methods provided by **twinBASIC** in the `VBA` namespace instead of calling the `RtlMoveMemory` API, which is slower.

2. Added some _"changes"_ to the `MemCopy`/`CopyBytes` methods to make them work in `twinBASIC`. But I wrapped them all within `#If TWINBASIC Then ...` instead of changing the existing code, avoiding to introduce any new bug to existing code bases, despite that that code works for both `VBA` and `twinBASIC`, with no noticeable drops in performance.

3. `MemZero`/`MemFill` seem to properly work in **twinBASIC**, removed `TWINBASIC` from the conditional compilation flags.

It's not yet ready to be merged as it needs more testing but at least it makes it usable in `twinBASIC` just the same way as in `VBA`.

2023-10-25 00:51 UTC, Theadd commented on src/LibMemory.bas
> +#If Win64 Or TWINBASIC Then
`twinBASIC` supports `LongLong` (8 bytes) in both **Win32** and **Win64**.

2023-10-25 00:53 UTC, Theadd commented on src/LibMemory.bas
>      #If Mac Or TWINBASIC Or (VBA7 = 0) Then
> `twinBASIC` supports `LongLong` (8 bytes) in both **Win32** and **Win64**.

2023-10-26 08:35 UTC, cristianbuse requested changes
Hi @Theadd ,

I just updated the [bug info](https://github.com/twinbasic/twinbasic/issues/1701#issuecomment-1780644109) in TB and so there is no need for the two ```#If TWINBASIC Then``` sections in ```MemCopy``` - i.e. the bug will surely get fixed soon. If you can remove those then I will push the other changes. Thanks!

2023-10-27 12:17 UTC, cristianbuse commented
Hi @Theadd ,

[This](https://github.com/twinbasic/twinbasic/issues/1704) was a problem as well. Once these 2 issues are sorted then no ```MemCopy``` should run fine.

2023-10-27 14:18 UTC, closed without merging

2023-10-27 14:18 UTC, cristianbuse commented
Many thanks @Theadd ,

I eventually pushed the changes [here](https://github.com/cristianbuse/VBA-MemoryTools/commit/ac61dc988fed54164c3909b39b2ee2f42f1815ad) with the exception of ```MemCopy``` which will follow after the 3 bugs raised in TB are resolved.

2023-10-29 16:11 UTC, Theadd commented
Hi @cristianbuse ,
My apologies for my absence these days.

Thank you =)

2023-10-30 09:50 UTC, cristianbuse commented
HI @Theadd ,

Please don't apologise because you've done nothing wrong. Many thanks!